# Created with komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: RussellBanks.Komac.Nightly
PackageVersion: Nightly
PackageLocale: en-US
Publisher: Russell Banks
PublisherUrl: https://github.com/russellbanks
PublisherSupportUrl: https://github.com/russellbanks/Komac/issues
Author: Russell Banks
PackageName: Komac
PackageUrl: https://github.com/russellbanks/Komac
License: GPL-3.0
LicenseUrl: https://github.com/russellbanks/Komac/blob/HEAD/LICENSE.md
ShortDescription: The Community Manifest Creator for WinGet
Tags:
- rust
- winget
- winget-cli
- winget-pkgs
ReleaseNotes: |-
  Komac Nightly Release
  These releases are updated on every commit.
ReleaseNotesUrl: https://github.com/russellbanks/Komac/releases/tag/nightly
ManifestType: defaultLocale
ManifestVersion: 1.12.0
