# Created with komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: RussellBanks.Komac.Nightly
PackageVersion: Nightly
InstallerLocale: en-US
InstallerType: inno
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: uninstallPrevious
ProductCode: '{776938BF-CF8E-488B-A3DF-8048BC64F2CD}_is1'
ReleaseDate: 2026-10-04
UnsupportedOSArchitectures:
- arm64
AppsAndFeaturesEntries:
- DisplayName: Komac (x64)
  DisplayVersion: 2.17.0
  ProductCode: '{776938BF-CF8E-488B-A3DF-8048BC64F2CD}_is1'
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/russellbanks/Komac/releases/download/nightly/komac-setup-nightly-x86_64-pc-windows-msvc.exe
  InstallerSha256: 93D9D0ED6E12E05F1EC6094087CF43815B8772FAC27E78CDB9BA52F291DB5523
  InstallerSwitches:
    Custom: /CURRENTUSER
  InstallationMetadata:
    DefaultInstallLocation: '%LocalAppData%\Programs\Komac'
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/russellbanks/Komac/releases/download/nightly/komac-setup-nightly-x86_64-pc-windows-msvc.exe
  InstallerSha256: 93D9D0ED6E12E05F1EC6094087CF43815B8772FAC27E78CDB9BA52F291DB5523
  InstallerSwitches:
    Custom: /ALLUSERS
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\Komac'
ManifestType: installer
ManifestVersion: 1.12.0
