# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: Romanitho.Winget-AutoUpdate
PackageVersion: 1.20.0
PackageLocale: en-US
Publisher: Romanitho
PackageName: Winget-AutoUpdate
License: MIT License
ShortDescription: WAU daily updates apps as system and notify connected users. (Allowlist and Blocklist support)
ManifestType: defaultLocale
ManifestVersion: 1.6.0
