# Created using wingetcreate 1.5.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.5.0.schema.json

PackageIdentifier: MotusSoftwareLtd.Pivotstick
PackageVersion: 5.1.31
PackageLocale: en-US
Publisher: Motus Software Ltd
PackageName: Pivotstick
License: Freeware
Copyright: Copyright Pіvotstіck
ShortDescription: Pivot makes it easy to create stick-figure animations
ManifestType: defaultLocale
ManifestVersion: 1.5.0
